version: '3.2'
services:
  server:
    build:
      context: ./server
      dockerfile: docker/local/Dockerfile
    ports:
      - "8000:3000"
      - "8080:8080"
      - "8001:3001"
    links:
      - mongodb
    volumes:
      - ./server:/var/www/html
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod --smallfiles
  client:
    build:
      context: ./app
      dockerfile: docker/local/Dockerfile
    ports:
      - "9000:3000"
    volumes:
      - ./app:/var/www/html
    links:
      - server
  admin:
    build:
      context: ./admin
      dockerfile: docker/local/Dockerfile
    ports:
      - "9001:3000"
    volumes:
      - ./admin:/var/www/html
    links:
      - server
